### ISSUE TITLE
Automatic module name conflicts with JDK module name

### ISSUE THREAD

**Issue by marschall** [javaee/javax.annotation#4]
The automatic module name introduced in #1 `java.annotation` conflicts with the module name in the JDK `java.xml.ws.annotation`. This means that modular applications requiring `java.xml.ws.annotation` can not use this module.

**Comment by bshannon** [comment]
Modular applications should use the java.annotation module.
The java.xml.ws.annotation module is a subset of the javax.annotation
classes that was needed by JAX-WS.

**Comment by marschall** [comment]
> Modular applications should use the java.annotation module.

It would be good if [JEP 320](http://openjdk.java.net/jeps/320) provided more clear guidance on this and how to avoid modular applications not starting due to split packages.
